apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nivo

resources:
- namespace.yaml
- secrets.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml
