name: Build and Push Image

on:
  workflow_call:
    inputs:
      ecr_repo_name:
        required: true
        type: string
    outputs:
      ecr_image_url:
        value: ${{ jobs.build-and-push.outputs.ecr_image_url }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    outputs:
      ecr_image_url: ${{ steps.build-push.outputs.image }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Generate Image Tag
      id: image-tag
      run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
    
    - name: Build and Push Image
      id: build-push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.ecr_repo_name }}
        IMAGE_TAG: ${{ steps.image-tag.outputs.tag }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f apps/api/Dockerfile .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
