name: Create Infrastructure

on:
  workflow_call:
    outputs:
      ecr_url: 
        value: ${{ jobs.create-infra.outputs.ecr_url }}
      cluster_name: 
        value: ${{ jobs.create-infra.outputs.cluster_name }}

jobs:
  create-infra:
    runs-on: ubuntu-latest
    
    outputs:
      ecr_url: ${{ steps.terraform-outputs.outputs.ecr_url }}
      test_ecr_url: ${{ steps.test-different-output.outputs.test_ecr_url }}
      cluster_name: ${{ steps.terraform-outputs.outputs.cluster_name }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Terraform Init
      working-directory: ./iac
      run: terraform init
    
    - name: Terraform Apply
      working-directory: ./iac
      run: terraform apply -auto-approve
    
    - name: Get Terraform Outputs
      working-directory: ./iac
      id: terraform-outputs
      run: |
        echo "ecr_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT
        echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
    
    - name: Debug Terraform Command
      working-directory: ./iac
      run: |
        echo "=== TERRAFORM OUTPUT COMMAND ==="
        echo "Raw ECR output: $(terraform output -raw ecr_repository_url)"
        echo "Raw cluster output: $(terraform output -raw cluster_name)"
        echo "All outputs:"
        terraform output
        echo "================================"
    
    - name: Debug Step Outputs
      run: |
        echo "=== STEP OUTPUTS ==="
        echo "ECR URL from step: '${{ steps.terraform-outputs.outputs.ecr_url }}'"
        echo "Cluster Name from step: '${{ steps.terraform-outputs.outputs.cluster_name }}'"
        echo "===================="
    
    - name: Test Different Output Name
      id: test-different-output
      run: |
        echo "test_ecr_url=${{ steps.terraform-outputs.outputs.ecr_url }}" >> $GITHUB_OUTPUT

  debug-job-outputs:
    needs: create-infra
    runs-on: ubuntu-latest
    steps:
    - name: Debug Job Outputs
      run: |
        echo "=== JOB OUTPUTS ==="
        echo "ECR URL from job: '${{ needs.create-infra.outputs.ecr_url }}'"
        echo "Test ECR URL from job: '${{ needs.create-infra.outputs.test_ecr_url }}'"
        echo "Cluster Name from job: '${{ needs.create-infra.outputs.cluster_name }}'"
        echo "==================="

