name: Create Infrastructure

on:
  workflow_call:

jobs:
  create-infra:
    runs-on: ubuntu-latest
    
    outputs:
      ecr_url: ${{ steps.ecr-url.outputs.ecr_url }}
      cluster_name: ${{ steps.cluster-name.outputs.cluster_name }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Terraform Init
      working-directory: ./iac
      run: terraform init
    
    - name: Terraform Apply
      working-directory: ./iac
      run: terraform apply -auto-approve
    
    - name: Get ECR Repository URL
      working-directory: ./iac
      id: ecr-url
      run: echo "ecr_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_OUTPUT
    
    - name: Get Cluster Name
      working-directory: ./iac
      id: cluster-name
      run: echo "cluster_name=$(terraform output -raw cluster_name)" >> $GITHUB_OUTPUT
